drop table groceries if exists;
create table groceries(
id decimal(19,2) generated by default as identity(start with 1, increment by 1) not null,
name varchar2(50) not null,
completed boolean default false,
created_date varchar2(11) not null
);